version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    volumes:
      - .:/rails
    command: bash -c "rm -f tmp/pids/server.pid && bin/rails server -b 0.0.0.0"
    ports:
      - "3000:3000"
    environment:
      - RAILS_ENV=development
      - RAILS_MASTER_KEY=${RAILS_MASTER_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - db
  
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: flash_ai_development
    ports:
      - "5432:5432"

volumes:
  postgres_data: 