# This file configures deployment on Render.com
# Documentation: https://render.com/docs/yaml-spec

services:
  - type: web
    name: flash-ai
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-ai-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RENDER
        value: true
      - key: WEB_CONCURRENCY
        value: 2

databases:
  - name: flash-ai-db
    databaseName: flash_ai_production
    ipAllowList: [] 