# This file configures deployment on Render.com
# Documentation: https://render.com/docs/yaml-spec

services:
  - type: web
    name: flash-ai
    runtime: ruby
    buildCommand: "chmod +x ./bin/render-build.sh && BUNDLE_FROZEN=0 BUNDLE_DEPLOYMENT=0 BUNDLE_WITHOUT='' SKIP_TAILWIND=true ./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: flash-ai-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RENDER
        value: true
      - key: WEB_CONCURRENCY
        value: 2
      - key: BUNDLE_FROZEN
        value: "false"
      - key: BUNDLE_DISABLE_VERSION_CHECK
        value: "true"
      - key: BUNDLE_WITHOUT
        value: "development:test"
      - key: BUNDLE_DEPLOYMENT
        value: "false"
      - key: RUBY_VERSION
        value: "3.3.7"
      - key: GEM_HOME
        value: /opt/render/project/.gems
      - key: PATH
        value: /opt/render/project/.gems/bin:/opt/render/project/rubies/ruby-3.3.7/bin:$PATH

databases:
  - name: flash-ai-db
    databaseName: flash_ai_production
    ipAllowList: []