name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  scan_ruby:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Fix script permissions
        run: bash .github/workflows/make_executable.sh

      - name: Install Brakeman 7.0.2
        run: gem install brakeman -v 7.0.2

      - name: Scan for common Rails security vulnerabilities using static analysis
        run: bin/brakeman --no-pager

  scan_js:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Fix script permissions
        run: bash .github/workflows/make_executable.sh

      - name: Scan for security vulnerabilities in JavaScript dependencies
        run: bin/importmap audit

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Fix script permissions
        run: bash .github/workflows/make_executable.sh

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Add overall job timeout

    # services:
    #  redis:
    #    image: redis
    #    ports:
    #      - 6379:6379
    #    options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libyaml-dev pkg-config google-chrome-stable

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true
          
      - name: Fix script permissions
        run: bash .github/workflows/make_executable.sh

      - name: List test files
        run: find test -type f -name "*_test.rb" | sort

      - name: Debug Rails environment
        run: |
          echo "Rails version:"
          bin/rails -v
          echo "Ruby version:"
          ruby -v
          echo "Environment:"
          bin/rails about

      - name: Prepare test database
        env:
          RAILS_ENV: test
          DISABLE_SPRING: true
        run: bin/rails db:test:prepare
        timeout-minutes: 2
        
      - name: Run unit tests with verbose output
        env:
          RAILS_ENV: test
          DISABLE_SPRING: true
          TESTOPTS: "--verbose"
          RAILS_LOG_TO_STDOUT: true
        run: bin/rails test --verbose
        timeout-minutes: 8
        
      - name: Run system tests
        env:
          RAILS_ENV: test
          HEADLESS: true
          DISABLE_SPRING: true
        run: bin/rails test:system
        timeout-minutes: 7

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
